import { test } from 'node:test';
import assert from 'node:assert/strict';
import request from 'supertest';
process.env.NODE_ENV = 'production';
process.env.MONGODB_URI = 'mongodb://127.0.0.1:27017/not-used-by-this-test';
process.env.JWT_SECRET = 'production-config-test-secret-with-48-characters';
process.env.CLIENT_ORIGIN = 'https://acadhub.example';
process.env.TRUST_PROXY = '1';
process.env.STORAGE_DRIVER = 's3';
process.env.S3_BUCKET = 'test-bucket';
process.env.CLAMAV_HOST = 'scanner.internal';
const { config, validateConfig, cookieOptions, authCookie } = await import('../src/config/env.js');
const { createApp } = await import('../src/app.js');
test('production configuration fails closed without secure storage and scanning', () => {
  validateConfig();
  const driver = config.storageDriver;
  config.storageDriver = 'local';
  assert.throws(validateConfig, /Production requires/);
  config.storageDriver = driver;
  const host = config.clamavHost;
  config.clamavHost = '';
  assert.throws(validateConfig, /Production requires/);
  config.clamavHost = host;
  const secret = config.jwtSecret;
  config.jwtSecret = 'replace-with-a-unique-random-secret-at-least-32-characters';
  assert.throws(validateConfig, /JWT_SECRET/);
  config.jwtSecret = secret;
  const origins = config.origins;
  config.origins = ['http://insecure.example'];
  assert.throws(validateConfig, /HTTPS/);
  config.origins = origins;
  assert.equal(cookieOptions.secure, true);
  assert.equal(cookieOptions.httpOnly, true);
  assert.equal(cookieOptions.sameSite, 'lax');
  assert.match(authCookie, /^__Host-/);
});
test('production denies plain HTTP and allows only configured forwarded HTTPS', async () => {
  const app = createApp();
  await request(app).get('/login').expect(400);
  const response = await request(app).get('/login').set('X-Forwarded-Proto', 'https');
  assert.ok([200, 404].includes(response.status));
  assert.ok(response.headers['content-security-policy']);
  assert.ok(response.headers['strict-transport-security']);
});
